name: Build and Push Prebuilt Devcontainer

on:
  push:
    branches:
      - main
    paths:
      - '.github/.devcontainer/**'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prebuild dev container image
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .github/.devcontainer
          imageName: ghcr.io/${{ github.repository }}/prebuilt-devcontainer
          cacheFrom: ghcr.io/${{ github.repository }}/prebuilt-devcontainer
          push: always
